const API =
  "https://script.google.com/macros/s/AKfycbzUWA0w2_MzltOtgGSBStBZKHzTaHt41DF2-3nw9niiMTOSHQRjNkbz5nETV8j_Mw0_/exec";

const HOKKAIDO_CENTER = [43.05, 142.35];
const HOKKAIDO_ZOOM = 7;
let summaries = [], catches = [], areaMasters = [], mapPoints = [], regulations = [];
let salmonMap = null, mapRendered = false;

async function getSheet(sheet) { const res = await fetch(`${API}?sheet=${encodeURIComponent(sheet)}`, {cache:"no-store"}); if(!res.ok) throw new Error(`${sheet}: HTTP ${res.status}`); const json=await res.json(); if(!json.ok) throw new Error(`${sheet}: API error`); return json.data||[]; }
function normalizeField(v){return String(v??"").trim()}
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function getDate(row){return normalizeField(row["実釣日"]||row["確認日"]||row["日付"])}
function getCatchCount(row){const n=Number(row["釣果本数"]);return Number.isFinite(n)?n:0}
function trustScore(v){const s=normalizeField(v).toUpperCase();if(s.startsWith("A"))return 3;if(s.startsWith("B"))return 2;if(s.startsWith("C"))return 1;return 0}
function isTrue(v){return ["TRUE","1","YES","有効","はい"].includes(normalizeField(v).toUpperCase())}
function validLatLng(lat,lng){const a=Number(lat),b=Number(lng);return Number.isFinite(a)&&Number.isFinite(b)&&a>=-90&&a<=90&&b>=-180&&b<=180}
function isHokkaidoLatLng(lat,lng){const a=Number(lat),b=Number(lng);return validLatLng(a,b)&&a>=40&&a<=46.5&&b>=138&&b<=147}

function setupAreas(){const s=document.getElementById("area");if(!s)return;const v=[...new Set(catches.map(x=>normalizeField(x["エリア"])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ja"));s.innerHTML=`<option value="all">すべて</option>`+v.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join("")}
function setupFishSpecies(){const s=document.getElementById("fish");if(!s)return;const v=[...new Set(catches.map(x=>normalizeField(x["魚種"])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ja"));s.innerHTML=`<option value="all">すべて</option>`+v.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join("")}

window.copyRecordId=async function(id,button){if(!id)return;try{await navigator.clipboard.writeText(id)}catch(_){const t=document.createElement("textarea");t.value=id;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()}if(button){const old=button.textContent;button.textContent="✓ コピー済";setTimeout(()=>button.textContent=old,1200)}};

function render(){
 const fish=document.getElementById("fish")?.value||"all",area=document.getElementById("area")?.value||"all",caught=document.getElementById("caught")?.value||"all",trust=document.getElementById("trust")?.value||"all",time=document.getElementById("time")?.value||"all",dateFrom=document.getElementById("dateFrom")?.value||"",dateTo=document.getElementById("dateTo")?.value||"",sort=document.getElementById("sort")?.value||"new";
 let rows=catches.filter(row=>{const rf=normalizeField(row["魚種"]),ra=normalizeField(row["エリア"]),rt=normalizeField(row["時間帯"]),rtr=normalizeField(row["信頼度"]),rd=getDate(row),c=getCatchCount(row);if(fish!=="all"&&rf!==fish)return false;if(area!=="all"&&ra!==area)return false;if(caught==="yes"&&c<=0)return false;if(caught==="no"&&c>0)return false;if(trust!=="all"&&trustScore(rtr)<trustScore(trust))return false;if(time!=="all"&&!rt.includes(time))return false;if(dateFrom&&rd&&rd<dateFrom)return false;if(dateTo&&rd&&rd>dateTo)return false;return true});
 if(sort==="new")rows.sort((a,b)=>getDate(b).localeCompare(getDate(a)));if(sort==="old")rows.sort((a,b)=>getDate(a).localeCompare(getDate(b)));if(sort==="catch")rows.sort((a,b)=>getCatchCount(b)-getCatchCount(a));if(sort==="trust")rows.sort((a,b)=>trustScore(b["信頼度"])-trustScore(a["信頼度"]));
 const ce=document.getElementById("count");if(ce)ce.textContent=`${rows.length}件`;const cards=document.getElementById("cards");if(!cards)return;if(!rows.length){cards.innerHTML=`<div class="empty">条件に一致する情報はありません。</div>`;return}
 cards.innerHTML=rows.map(row=>{const tc=normalizeField(row["信頼度"]).charAt(0).toUpperCase();const rid=normalizeField(row["ID"]||row["管理コード"]);return `<article class="card"><div class="top"><h3>${escapeHtml(row["エリア"]||"未分類")}</h3><span class="chip ${escapeHtml(tc)}">信頼度 ${escapeHtml(row["信頼度"]||"-")}</span></div>${rid?`<div class="record-id"><span>ID: ${escapeHtml(rid)}</span><button type="button" onclick='copyRecordId(${JSON.stringify(rid)},this)'>📋 コピー</button></div>`:""}<div class="meta">${escapeHtml(getDate(row)||"-")}${row["時間帯"]?`・${escapeHtml(row["時間帯"])}`:""}</div>${row["具体地点"]?`<span class="chip">📍 ${escapeHtml(row["具体地点"])}</span>`:""}${row["釣果本数"]!==""?`<span class="chip">🎣 ${escapeHtml(row["釣果本数"])}本</span>`:""}${row["釣法"]?`<span class="chip">${escapeHtml(row["釣法"])}</span>`:""}${row["風・波・濁り"]?`<p>${escapeHtml(row["風・波・濁り"])}</p>`:""}${row["メモ"]?`<p>${escapeHtml(row["メモ"])}</p>`:""}<div class="meta">${escapeHtml(row["情報源"]||row["情報区分"]||"")}</div></article>`}).join("");
}
function getLatestSummary(){if(!summaries.length)return[];const d=summaries.map(x=>normalizeField(x["日付"])).filter(Boolean).sort();const l=d[d.length-1];return summaries.filter(x=>normalizeField(x["日付"])===l)}
function renderOtherFish(row){const target="今釣れてる魚(アキアジ以外)";const key=Object.keys(row||{}).find(name=>name.normalize("NFKC").replace(/\s+/g,"")===target);const value=normalizeField(key?row[key]:"");return `<div class="detail other-fish"><strong>🐟 今釣れてる魚（アキアジ以外）</strong><p style="white-space:pre-wrap;overflow-wrap:anywhere;">${escapeHtml(value||"情報未確認")}</p></div>`}
function renderSummary(){const rows=getLatestSummary().sort((a,b)=>Number(a["順位"]||999)-Number(b["順位"]||999)),hero=document.querySelector("#summary .hero"),box=document.getElementById("summaryCards");if(!rows.length){if(hero)hero.innerHTML=`<small>Google Sheet LIVE</small><h3>最新情報なし</h3>`;if(box)box.innerHTML=`<div class="empty">日次サマリーがありません。</div>`;return}const latestDate=normalizeField(rows[0]["日付"]);if(hero)hero.innerHTML=`<small>Google Sheet LIVE</small><h3>${escapeHtml(latestDate)} 最新状況</h3>`;if(!box)return;box.innerHTML=rows.map(row=>`<article class="card"><div class="top"><h3>${escapeHtml(row["順位"]||"-")}位　${escapeHtml(row["エリア"]||"-")}</h3></div><p><strong>${escapeHtml(row["総合判定"]||"-")}</strong></p>${row["直近実釣果"]?`<p>🎣 ${escapeHtml(row["直近実釣果"])}</p>`:""}${row["群れ・接岸"]?`<p>🐟 ${escapeHtml(row["群れ・接岸"])}</p>`:""}${row["風・波・濁り"]?`<p>🌊 ${escapeHtml(row["風・波・濁り"])}</p>`:""}${row["有望時間・潮"]?`<p>⏰ ${escapeHtml(row["有望時間・潮"])}</p>`:""}${row["狙い目・注意"]?`<p>💡 ${escapeHtml(row["狙い目・注意"])}</p>`:""}${renderOtherFish(row)}<div class="meta">更新 ${escapeHtml(row["更新時刻"]||"-")}</div></article>`).join("")}
function renderAnalysis(){const box=document.getElementById("analysisBox");if(!box)return;if(!catches.length){box.innerHTML=`<small>Google Sheet LIVE</small><h3>分析対象データなし</h3>`;return}const caughtRows=catches.filter(x=>getCatchCount(x)>0),areaCounts={};caughtRows.forEach(row=>{const a=normalizeField(row["エリア"])||"未分類";areaCounts[a]=(areaCounts[a]||0)+getCatchCount(row)});const ranking=Object.entries(areaCounts).sort((a,b)=>b[1]-a[1]);box.innerHTML=`<small>Google Sheet LIVE</small><h3>登録 ${catches.length}件</h3><p>釣果あり記録：${caughtRows.length}件</p>${ranking.length?ranking.map(([a,c],i)=>`<p>${i+1}. ${escapeHtml(a)}：${c}本</p>`).join(""):"<p>釣果数データはまだありません。</p>"}`}
function findSummaryForArea(master){const l=getLatestSummary(),c=normalizeField(master["エリアコード"]),r=normalizeField(master["地域"]),n=normalizeField(master["表示名"]);return l.find(x=>(c&&normalizeField(x["エリアコード"])===c)||(r&&normalizeField(x["エリア"])===r)||(n&&normalizeField(x["エリア"])===n))}
function findLatestCatch(master){const c=normalizeField(master["エリアコード"]),r=normalizeField(master["地域"]),n=normalizeField(master["表示名"]);return catches.filter(x=>(c&&normalizeField(x["エリアコード"])===c)||(r&&normalizeField(x["エリア"])===r)||(n&&normalizeField(x["エリア"])===n)).sort((a,b)=>getDate(b).localeCompare(getDate(a)))[0]}
function markerColor(summary){const t=normalizeField(summary?.["総合判定"]);if(t.includes("有望")||t.includes("魚は確認")||t.includes("重点"))return"#2ecc71";if(t.includes("監視")||t.includes("新報待ち")||t.includes("様子見"))return"#f1c40f";return"#95a5a6"}
function makeDivIcon(color){return L.divIcon({className:"salmon-div-icon",html:`<div style="width:22px;height:22px;border-radius:50%;background:${color};border:3px solid white;box-shadow:0 1px 6px rgba(0,0,0,.45);"></div>`,iconSize:[22,22],iconAnchor:[11,11],popupAnchor:[0,-12]})}
function makeEmojiIcon(emoji){return L.divIcon({className:"emoji-div-icon",html:`<div style="font-size:26px;line-height:28px;text-shadow:0 1px 4px rgba(255,255,255,.95),0 1px 5px rgba(0,0,0,.35);">${emoji}</div>`,iconSize:[30,30],iconAnchor:[15,15],popupAnchor:[0,-15]})}
function summaryPopup(master,summary,latestCatch){const name=normalizeField(master["表示名"]||master["地域"]||"未設定"),text=latestCatch?`${getDate(latestCatch)||"日付不明"} / ${normalizeField(latestCatch["具体地点"])||"地点不明"} / ${normalizeField(latestCatch["釣果本数"])||"0"}本`:"釣果記録なし";return `<div style="min-width:220px;max-width:280px;"><strong>${escapeHtml(name)}</strong><hr><div><b>総合判定:</b> ${escapeHtml(summary?.["総合判定"]||"未確認")}</div><div><b>直近実釣:</b> ${escapeHtml(text)}</div><div><b>群れ・接岸:</b> ${escapeHtml(summary?.["群れ・接岸"]||"未確認")}</div><div><b>狙い目:</b> ${escapeHtml(summary?.["狙い目・注意"]||"未確認")}</div><br><button onclick="openAreaSearch('${escapeHtml(normalizeField(master["地域"]||name))}')">このエリアの釣果を見る</button></div>`}
function mapPointPopup(point){const type=normalizeField(point["種別"]),name=normalizeField(point["地点名"]||point["名称"]||"地点"),note=normalizeField(point["注意・メモ"]||point["備考"]||point["メモ"]);return `<div style="min-width:200px;max-width:280px;"><strong>${escapeHtml(name)}</strong><hr><div><b>種別:</b> ${escapeHtml(type||"未設定")}</div>${note?`<div>${escapeHtml(note)}</div>`:""}</div>`}
function regulationPopup(row){const river=normalizeField(row["河川名"]||"河川名未確認"),start=normalizeField(row["開始日"]),end=normalizeField(row["終了日"]),left=normalizeField(row["左岸距離"]),right=normalizeField(row["右岸距離"]),offshore=normalizeField(row["沖合距離"]),source=normalizeField(row["公式情報源URL"]),checked=normalizeField(row["最終確認日時"]);return `<div style="min-width:220px;max-width:300px;"><strong>⚠️ ${escapeHtml(river)} 河口規制</strong><hr><div><b>期間:</b> ${escapeHtml(start||"未確認")} ～ ${escapeHtml(end||"未確認")}</div><div><b>左岸:</b> ${escapeHtml(left||"未確認")}</div><div><b>右岸:</b> ${escapeHtml(right||"未確認")}</div><div><b>沖合:</b> ${escapeHtml(offshore||"未確認")}</div><div><b>最終確認:</b> ${escapeHtml(checked||"未確認")}</div>${source?`<div><a href="${escapeHtml(source)}" target="_blank" rel="noopener noreferrer">公式根拠を開く</a></div>`:""}</div>`}
function renderMap(){if(mapRendered||!window.L)return;const el=document.getElementById("salmonMap");if(!el)return;salmonMap=L.map("salmonMap",{zoomControl:true,minZoom:5,maxZoom:18}).setView(HOKKAIDO_CENTER,HOKKAIDO_ZOOM);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap"}).addTo(salmonMap);areaMasters.filter(r=>isHokkaidoLatLng(r["緯度"],r["経度"])).forEach(m=>{const lat=Number(m["緯度"]),lng=Number(m["経度"]),s=findSummaryForArea(m),lc=findLatestCatch(m);L.marker([lat,lng],{icon:makeDivIcon(markerColor(s))}).addTo(salmonMap).bindPopup(summaryPopup(m,s,lc))});mapPoints.filter(r=>isTrue(r["有効"])&&isHokkaidoLatLng(r["緯度"],r["経度"])).forEach(p=>{const lat=Number(p["緯度"]),lng=Number(p["経度"]),type=normalizeField(p["種別"]);let emoji="📍";if(type.includes("漁業"))emoji="⚓";else if(type.includes("船"))emoji="🚤";else if(type.includes("釣"))emoji="🐟";if(type.includes("駐"))emoji="🚗";L.marker([lat,lng],{icon:makeEmojiIcon(emoji)}).addTo(salmonMap).bindPopup(mapPointPopup(p))});regulations.filter(r=>isTrue(r["現在規制中"])&&normalizeField(r["座標確認状態"])==="検証済"&&isHokkaidoLatLng(r["緯度"],r["経度"])).forEach(r=>L.marker([Number(r["緯度"]),Number(r["経度"])],{icon:makeEmojiIcon("⚠️")}).addTo(salmonMap).bindPopup(regulationPopup(r)));setTimeout(()=>{salmonMap.invalidateSize();salmonMap.setView(HOKKAIDO_CENTER,HOKKAIDO_ZOOM,{animate:false})},100);mapRendered=true}
window.openAreaSearch=function(region){const s=document.getElementById("area");if(s){const o=[...s.options].find(o=>o.value===region||region.includes(o.value)||o.value.includes(region));s.value=o?o.value:"all"}document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById("search")?.classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page==="search"));render()};
function setupEvents(){["fish","area","caught","trust","time","dateFrom","dateTo","sort"].forEach(id=>document.getElementById(id)?.addEventListener("change",render));document.getElementById("reset")?.addEventListener("click",()=>{["fish","area","caught","trust","time","sort"].forEach(id=>{const e=document.getElementById(id);if(e)e.value=id==="sort"?"new":"all"});["dateFrom","dateTo"].forEach(id=>{const e=document.getElementById(id);if(e)e.value=""});render()});document.querySelectorAll("nav button").forEach(b=>b.addEventListener("click",()=>{const p=b.dataset.page;document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(p)?.classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));if(p==="map"){renderMap();setTimeout(()=>salmonMap?.invalidateSize(),150)}}))}
async function load(){try{const [sd,cd,ad,pd,rd]=await Promise.all([getSheet("日次サマリー"),getSheet("釣果・現地情報"),getSheet("エリアマスタ"),getSheet("マップ地点"),getSheet("河口規制マスタ")]);summaries=sd;catches=cd;areaMasters=ad;mapPoints=pd;regulations=rd;setupFishSpecies();setupAreas();renderSummary();render();renderAnalysis();console.log(`読込完了: 日次${summaries.length} / 釣果${catches.length} / エリア${areaMasters.length} / 地点${mapPoints.length} / 規制${regulations.length}`)}catch(error){console.error(error);const h=document.querySelector("#summary .hero");if(h)h.innerHTML=`<small>ERROR</small><h3>Google Sheetの取得に失敗しました</h3><p>${escapeHtml(error.message)}</p>`}}
setupEvents();load();